### ISSUE TITLE
Sanint

### ISSUE THREAD

**Issue by juev** [stekkko/resume#1]
Привет, насколько вижу, в резюме в имени города есть ошибка:

<img width="261" alt="Снимок экрана 2022-01-17 в 09 33 28" src="https://user-images.githubusercontent.com/114635/149719357-352b4a9d-6731-46dc-a16e-eb3b5442f00f.png">

Хотя может я не знаю, как правильно пишется Санк-Питербург на английском? Но вроде ниже по тексту у тебя корректное именование.

И так же вопрос, что использовал для генерации резюме? Какое ПО? Исходников не будет?

**Comment by stekkko** [comment]
https://www.overleaf.com
там либо сам на  Latex пишешь, либо берешь готовый шаблон и редактируешь
P.S спасибо что нашел ошибку

**Comment by stekkko** [comment]
Я потом по сути конвертнул PDF в index.html и запустил на GitHub Pages через рандомный сервис в гугле
